// loaders
export const LOGIN_ENABLE_LOADER = "LOGIN_ENABLE_LOADER";
export const LOGIN_DISABLE_LOADER = "LOGIN_DISABLE_LOADER";

// theming
export const TOGGLE_THEME = "TOGGLE_THEME";

// login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGIN_LOADING_ENDED = "LOGIN_LOADING_ENDED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";

// location
export const CURRENT_LOCATION_REQUEST = "CURRENT_LOCATION_REQUEST";
export const CURRENT_LOCATION_REQUEST_SUCCESS =
  "CURRENT_LOCATION_REQUEST_SUCCESS";
export const CURRENT_LOCATION_REQUEST_FAIL = "CURRENT_LOCATION_REQUEST_FAIL";

// favorite

export const FV_REQUEST = "FV_REQUEST";
